# create the namespace
---
apiVersion: v1
kind: Namespace
metadata:
   name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/service_account.yaml
# @formatter:off
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
  name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/webhookSecretAndConfigurations.yaml
# @formatter:off
  ## We generate one root CA and server certificate which are as
  ## by the webhook caBundle and server secrete. We place the both
  ## secret and webhook config files here so they share the same root CA
  ## See https://github.com/helm/helm/issues/6456#issuecomment-701727623---
kind: Secret
apiVersion: v1
type: kubernetes.io/tls
metadata:
  name: bookkeeper-operator-bookkeeper-operator-webhook-secret
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMakNDQXhhZ0F3SUJBZ0lRSTRLb3RWc1pJTXZzTmZCekQvVUxxakFOQmdrcWhraUc5dzBCQVFzRkFEQVoKTVJjd0ZRWURWUVFERXc1M1pXSnZiMnN0Y205dmRDMWpZVEFlRncweU5UQXhNREl3TWpVM05URmFGdzB6TkRFeQpNekV3TWpVM05URmFNRUl4UURBK0JnTlZCQU1UTjJKdmIydHJaV1Z3WlhJdGIzQmxjbUYwYjNJdFltOXZhMnRsClpYQmxjaTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRREVpWnRkQWQvUWhySXBCSkJVOERkWkdlZFVEYktKVmRvL2JnRTRzQXNMYU5DRwp6UGQ2VmR0djEwTnoyT3JRVmJlcFlVT2ZLa3pkNU5nb3RYTUhaS09GdkJzcVBBTXVhNXE3Z05lSEZoTVdWSVRrClBmRFZ3NTNRUmxPQlk1b1BjTzlLa0ZQOERWM2lUT2tVbGY0MHl0YmRaT1dGdStESUtHSG9hWkNiUStsMEdZYTAKRm1DWE9oSjJycXRnWXRhaTczemRXQXl1WnVrbUU2eGE5cnZBc1g5Y3JoaW5FSkNZeTNYUEFoL1FmSURmVldnSQptRG0rVTUvd3dDR2Z1R3pVNnhlNTZPNW5xZ2RQdWVuaktKVmFVMnFmaWEzOUlyUktubVY5Tm9VRTVFeFFBWXlaCkVBd2hhU3hyR2RQM1Jkdm1tdDBWR21JTEVsN0owcTdpdHMrSXdBM0ZBZ01CQUFHamdnRkhNSUlCUXpBT0JnTlYKSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZApFd0VCL3dRQ01BQXdId1lEVlIwakJCZ3dGb0FVRHpIdUFGOHdSaFdRbzNVWWhrU1BaR2kyanQ0d2dlSUdBMVVkCkVRU0IyakNCMTRJM1ltOXZhMnRsWlhCbGNpMXZjR1Z5WVhSdmNpMWliMjlyYTJWbGNHVnlMVzl3WlhKaGRHOXkKTFhkbFltaHZiMnN0YzJWeWRtbGpaWUpMWW05dmEydGxaWEJsY2kxdmNHVnlZWFJ2Y2kxaWIyOXJhMlZsY0dWeQpMVzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNWliMjlyYTJWbGNHVnlMVzl3WlhKaGRHOXlnazlpCmIyOXJhMlZsY0dWeUxXOXdaWEpoZEc5eUxXSnZiMnRyWldWd1pYSXRiM0JsY21GMGIzSXRkMlZpYUc5dmF5MXoKWlhKMmFXTmxMbUp2YjJ0clpXVndaWEl0YjNCbGNtRjBiM0l1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUFLdWh2bEI1WjhVaCttYXkzeFZpTzgwWiszWEY3QzRtTm1sUWU0VWRlNHZDcGcydks0OEpsbDJLdExVd2x2Ck1JbjM3SzRyazg3Nkc0ZHllUHJLeEFFb052SFo4Q0kyUHVHYk84bHlvMjRLNmhkNUlJb296TlZoSU5ZUXEzWmMKSlVRS3FoL3pMUnVtWEI1VFI3YVZuSjlQU3ZHWnFza01WZ21rMHpqWlJyYjkraG9Oc2VnVGh6c21wbmNMSFRHWgp1Q2d3Z2d3dExEVEFLaW5xNG1Zd3U2eHlsSVJYQXFvanh1RVFwQllSMWo0MmJkc3BXM3dQV0JZRC95ZWRGWCt6ClJMSi81VU5pekIwc3JDTUwxdm1CNVlQcmNHUmM5WFZSUGR4bGsza1FMaHJNQU90Y2VUa2c5TlBFNGQwVjNZV1kKWWl1bnVmYXBQbk1LT1RHWkt4b09JUXptCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeEltYlhRSGYwSWF5S1FTUVZQQTNXUm5uVkEyeWlWWGFQMjRCT0xBTEMyalFoc3ozCmVsWGJiOWREYzlqcTBGVzNxV0ZEbnlwTTNlVFlLTFZ6QjJTamhid2JLandETG11YXU0RFhoeFlURmxTRTVEM3cKMWNPZDBFWlRnV09hRDNEdlNwQlQvQTFkNGt6cEZKWCtOTXJXM1dUbGhidmd5Q2hoNkdtUW0wUHBkQm1HdEJaZwpsem9TZHE2cllHTFdvdTk4M1ZnTXJtYnBKaE9zV3ZhN3dMRi9YSzRZcHhDUW1NdDF6d0lmMEh5QTMxVm9DSmc1CnZsT2Y4TUFobjdoczFPc1h1ZWp1WjZvSFQ3bnA0eWlWV2xOcW40bXQvU0swU3A1bGZUYUZCT1JNVUFHTW1SQU0KSVdrc2F4blQ5MFhiNXByZEZScGlDeEpleWRLdTRyYlBpTUFOeFFJREFRQUJBb0lCQUVvc25RUW5GdTgrUnJNUQpVK0Nhb0dqeVM4bi9PV2gzakZ6d0NXbjVsdEdCaDJHNHJaWHdIVmRDYU9TcDgwVVpkSzFxVmZrV0g5aUc2OFhCClpWNWU3eEFrQkNTV2JhVHhXMzUwaStNaHc2WmowNXZJZk1KUWg1ajVVYjY5ZG9GcFlBWkdIa3c4UnppSFNsaEkKbTU0VkI2NmF5NzBEUVR5SmNSb2o3VDJNRGVtUXAwdWZna2s5MUNTZ3NlT2tsSWFBNEszNUVaQnJjMkxlS1QvawpmLzdiMGJ0bWI0b09BU2ZFenN3bjBYNGZVTlA0eFJuRUx1Mi9Mc1ZyU01WaTVCSkN4MnlrcExwZ3dITCtUZVkzClBib1NnU3RFQ1craGYvNWVkcmJEclhRbmw5anIrQWJRWWVqaEtxYnVUWkh0bEs5TXlsU01HR1owdGRPTG1hMFMKWXpVUldta0NnWUVBMk9EOFBUSkZ6VFl0Mk94Y2p1VytuQ3FPMTJzMEIwSDBxeDlteWJaRmFBMU5vaXExaWptZwpyR01YRVJhR2xUbHRUQUx4RW8ya3lhL3VvckNEK2VQSmtIeHB5Q2thb3FSb1lBdDdvQlVicjgwa3IrelduUXdPCmMyZ3Z1VStHSXM1d3RjaDJDRHAxNytqMGh2ZUZWR3FiLzFHenVPUjZ5bml2eXdVM2dIUHlsbnNDZ1lFQTUvMU4KTk90eFNTT09Pd0cyZiszU2JsSVpBeWNKTWEvd3dsMk9BRFRSZVlwMEhrd3cySkIvQiswa3UyaVVYdjlMWmNBMgpCTjZ3S0FpZDJNUThFb0liVWt1Q2trb0RROElwN2Z3alBXcjQrWGFUajR4bi82Vy9rTkhVV05MbGNERXdTSWl2ClNhRFR4dDRyVEhWYjVpTXlhZWtzc0xOYzdzRHh2QzBHNmRJKzJMOENnWUE0a1laNVY5R0pFeWFtUEJCd1hWQjQKWDBsZXV1R1pPd1RjVlpaejZveno5UFJZNWhidjlOUUo0dGF6YUZLMlBZSmFuekhPQ3cvK1kxczFLQ0ZrWHB2RwppZ3oxWG5OS0ZPUDhtVUlub1JuVm93Wjh0S1BOMXNVMktPaTV4eHBQbmRVY05TdEVQaXRnNWp4UnIrSWhBS1dyCjFOMnh6amFROVNXMUtLa3ZZZzdXWFFLQmdRQ2xCZWVVM0dLQ2ozdE9lQ0oxRUJ5ZmcyRHRnQ2duSXl1VloyMXEKc2lmTVdIUFBWWTF0a0NQODVIRTdxdUhZVGF3NW5pZ1BBTVc0UktEY0lJTkcreXdxTnpLVGszaU5DNkk5K3h5cQpSTjBFdjVlcUJrdTRiQlJBRlRNRFdFb0RxOG5YM3ZzcDJmQ3J4MEJ2ckJBS1BrRlBXNklCdENWSVpSSFFOUXQwCjZxendDd0tCZ1FEQ28zbFVrYXV4N1o0bm1yUnBISExzbE40Mkk5Uk9hMmF1ejBoRHA0Y3hlZHMxWnJmME00R0sKTkc1cWtlWU43RytZeUNJQkJYNE9paWUwLzlvNE5MRXNhRWVJQy8rendod3FwN0pSNE0xa0VrK1hDYllXUGYxWAp3QWhESXc4U2VJRFA5WFFLcnNGZVNUd2VNYXFmTFAwS2FGU0JwNmJFTWk2TWZXSWRhVVNjeUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: bookkeeper-operator/templates/clusterrole.yaml
# @formatter:off
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookkeeper-operator-manager-role
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - apps
      - batch
      - policy
      - extensions
    resources:
      - jobs
      - pods
      - events
      - secrets
      - services
      - configmaps
      - deployments
      - statefulsets
      - poddisruptionbudgets
      - persistentvolumeclaims
    verbs:
      - '*'
---
# Source: bookkeeper-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookkeeper-operator-proxy-role
rules:
  - apiGroups: [ "authentication.k8s.io" ]
    resources:
      - tokenreviews
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources:
      - subjectaccessreviews
    verbs: [ "create" ]
---
# Source: bookkeeper-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookkeeper-operator-metrics-reader
rules:
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "get" ]
---
# Source: bookkeeper-operator/templates/clusterrolebinding.yaml
# @formatter:off
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bookkeeper-operator-manager-role-binding
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bookkeeper-operator-manager-role
subjects:
  - kind: ServiceAccount
    namespace: bookkeeper-operator
    name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/role.yaml
# @formatter:off
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bookkeeper-operator-leader-election-role
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Source: bookkeeper-operator/templates/rolebinding.yaml
# @formatter:off
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bookkeeper-operator-leader-election-role-binding
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bookkeeper-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    namespace: bookkeeper-operator
    name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/services.yaml
# @formatter:off
apiVersion: v1
kind: Service
metadata:
  name: bookkeeper-operator-bookkeeper-operator-webhook-service
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookkeeper-operator-controller-manager-metrics-service
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  
  selector:
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/deployment.yaml
# @formatter:off
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookkeeper-operator
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.13
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.13"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bookkeeper-operator
      app.kubernetes.io/instance: bookkeeper-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bookkeeper-operator
        app.kubernetes.io/instance: bookkeeper-operator
    spec:
      containers:
        - name: bookkeeper-operator
          image: monime/bookkeeper-operator:v0.2.13
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsUser: 65534
          env:
            - name: LEADER_ELECTION_NAMESPACE
              value: bookkeeper-operator
      volumes:
        - name: webhook-certs
          secret:
            secretName: bookkeeper-operator-bookkeeper-operator-webhook-secret
      serviceAccountName: bookkeeper-operator
