# create the namespace
---
apiVersion: v1
kind: Namespace
metadata:
   name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/service_account.yaml
# @formatter:off
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
  name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/webhookSecretAndConfigurations.yaml
# @formatter:off
  ## We generate one root CA and server certificate which are as
  ## by the webhook caBundle and server secrete. We place the both
  ## secret and webhook config files here so they share the same root CA
  ## See https://github.com/helm/helm/issues/6456#issuecomment-701727623---
kind: Secret
apiVersion: v1
type: kubernetes.io/tls
metadata:
  name: bookkeeper-operator-bookkeeper-operator-webhook-secret
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMekNDQXhlZ0F3SUJBZ0lSQU8welBUVnQrazFiMDBhZ0RKNFhiT3d3RFFZSktvWklodmNOQVFFTEJRQXcKR1RFWE1CVUdBMVVFQXhNT2QyVmliMjlyTFhKdmIzUXRZMkV3SGhjTk1qTXhNVEUzTURVeU5UVXpXaGNOTXpNeApNVEUwTURVeU5UVXpXakJDTVVBd1BnWURWUVFERXpkaWIyOXJhMlZsY0dWeUxXOXdaWEpoZEc5eUxXSnZiMnRyClpXVndaWEl0YjNCbGNtRjBiM0l0ZDJWaWFHOXZheTF6WlhKMmFXTmxNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUE3Q3g4UHhnc21icDNmU2tOTVU2Tnp2Q28rcDJqbkRBd3g5Z3JNd1pkNDdLeApmS0FvUnR4WHNmTnFEajZSNkh1YnF6Y2R3WVM4WVhmUXkwL3JBSWlmUjZES0IxcVY1cW9qSlB2MVJRa0xnZFFoCnR5Rm00dnY1Ym5Ud2E5NE5pT1RqQUdzVUFmK09vZ1B0c3kwZ2VGai81M2MyN2tnQmh0QlNOa1FWakU1VWRnSDIKUW5sdXFnRUQyK0EvTXo2b0NtcGMwazExeWJSZ3BqM09UT0R3VmFJQi9PcTVqNm1nMzhsenhzTXo0T2VtLyszOAo5RnA0SHZMbEQ0c0huK00vZm42WElJYWxwcjhOTjFVd3JKY1hsVjN4VFNDMXVuUGxqQ2pWNStFcGYvUERNSEtICm11S1hscVNVbXZPNHFTazRHck11d3VVUXJRS2JxenFXNjRIQTlhWUM1d0lEQVFBQm80SUJSekNDQVVNd0RnWUQKVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVgpIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRklaZWpkTlE0OHNGL0huWFV5YWxMSW54c09UV01JSGlCZ05WCkhSRUVnZG93Z2RlQ04ySnZiMnRyWldWd1pYSXRiM0JsY21GMGIzSXRZbTl2YTJ0bFpYQmxjaTF2Y0dWeVlYUnYKY2kxM1pXSm9iMjlyTFhObGNuWnBZMldDUzJKdmIydHJaV1Z3WlhJdGIzQmxjbUYwYjNJdFltOXZhMnRsWlhCbApjaTF2Y0dWeVlYUnZjaTEzWldKb2IyOXJMWE5sY25acFkyVXVZbTl2YTJ0bFpYQmxjaTF2Y0dWeVlYUnZjb0pQClltOXZhMnRsWlhCbGNpMXZjR1Z5WVhSdmNpMWliMjlyYTJWbGNHVnlMVzl3WlhKaGRHOXlMWGRsWW1odmIyc3QKYzJWeWRtbGpaUzVpYjI5cmEyVmxjR1Z5TFc5d1pYSmhkRzl5TG5OMll6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBZWY2YyttVi9GVUFabFdtSDdVZzVoOURnbjdTRmZYL2VvcVR1R0xtWG0yVStVZEUrUlR1R1JEUmpFYmh5ClZYelBrRDc4VDhGa1lkWmRzV092YUtFaHJiUkUrL1FxM1pYMnp0ZHVobHNxaC9GdWIrR2N3OWJ0dDh4QSs4blIKV3NHV21JTVRDa1dxRlFrYk5GckxTT0FIMlRJOFhlYTgxQnFmd2tsTUpZbmVRSkxYM0RsOVlBcDBqRWJ5cTB0bAo0N0MwSEgwaGFUL0hxdFlyaHE3NWJ1b1RodzFvTXlZdEpzWHFvaWxlcUtpVmczQjdiWGxVM2htZGVGWUpnTVpBCm1LVzhQbXhxSjZ3OXRaaUo1SmNIa1pxa0hoNzUvMXlnanpyVUxON1VzSXE4MTFEMEJEZU81UXNTMXNZUExISmMKNVVaeFVBRC9qVVRPVkdKSThCOG0xSVVEdXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBN0N4OFB4Z3NtYnAzZlNrTk1VNk56dkNvK3Ayam5EQXd4OWdyTXdaZDQ3S3hmS0FvClJ0eFhzZk5xRGo2UjZIdWJxemNkd1lTOFlYZlF5MC9yQUlpZlI2REtCMXFWNXFvakpQdjFSUWtMZ2RRaHR5Rm0KNHZ2NWJuVHdhOTROaU9UakFHc1VBZitPb2dQdHN5MGdlRmovNTNjMjdrZ0JodEJTTmtRVmpFNVVkZ0gyUW5sdQpxZ0VEMitBL016Nm9DbXBjMGsxMXliUmdwajNPVE9Ed1ZhSUIvT3E1ajZtZzM4bHp4c016NE9lbS8rMzg5RnA0Ckh2TGxENHNIbitNL2ZuNlhJSWFscHI4Tk4xVXdySmNYbFYzeFRTQzF1blBsakNqVjUrRXBmL1BETUhLSG11S1gKbHFTVW12TzRxU2s0R3JNdXd1VVFyUUticXpxVzY0SEE5YVlDNXdJREFRQUJBb0lCQVFDWFZ2cFhSQnB3ZURqUgpqMWpRMjlHclpqUWlSSm52SUVKaURYZkJQcmN6amZLR05lc1pYV0VrdXlLZTlpRnhwS1BnVjNWTjZNeitlRlRuCnM5S1hpUFRvWlhTUXVjK00vRUdCRmFQYUZTMjJpRVVDb1BqWlF6WlhQY0JDbnd4MVNKYmVVYitFZUVyaUx6cEcKc3dnM2xuQ0Yxckx3aGx2VUUvSmFxODVURm02eEh0MTJDSHJGN1FQaTd6Q2dGZFhrZUphYVpnNkJ2elV1elp2awpkcFVKL2dsY1dvV0lVYW44ekhGRGdxdzBOaHVqazJTWS9BTkhQN01NaHV4bHJEL1BDT1NmRXVzWldsYW1Jby9DClhrZGVSYnhhcTVQS21xWWZyUEtzV2E4ZWx4SXlVMHIxSW1MODl0VmRoazY4TUJKWnIwZkZjb05wdHpPMDdJS2cKVTJvUitTVmhBb0dCQU82NjlZdUtIR2pNZmJiMlNXcWtJYkFEOHYxdUtSMlJDck1RU0hJaFpBdUpNSVdXZzMwYgpLTEw5Tjg2VjJ6ODQxNC85L0VFaGJidGdBWFF0M0FZYkVRRDBRb2UxR3NYQWlYbE1UWnYrVzRYZVorN3hNZXVQClZNMVRLeE9ZdmpjdEt5RitNWGVmV0NJWlhsK09GdlVSZklQVUcyWVRhZjN3NGJvYnNaeStzTEdWQW9HQkFQMUMKTG9RMTBKbXg1N0VpSHhISnh1TjBoWG9Lam9MMGFWZStUTE5iS2RONHpMOUlMaGxYWm9Oajl0U0RGMjF5MzZqawo1K2ZTZzZsVXJGMkJpRFBoMDZINWdMNnpnUjVUbW5OWFUzSG9CMEdENHdySEh4cWZaYTlVaUVYS1RUZmh5cVZ1CnpudEpDMjFpTGdLYVlqazVKQ0NtbVc1WTl1d0ZsN056NEN2S0YzdUxBb0dCQUxZaVRWTzRleFE1YjNBM1ZxdlYKclIzczVXWVV0YW1wRHRDdWk1Y0hncHlLZmtwdEdzUklCRFVLbTVreEc2U1FhV1dpRU9KZjdxZ1dCd1hzTndFeApoVGVGSTMwRjN2Y2dmY0hkUlJqT1ptVXIyWCtpNU1NakJ6L2ZRKzRmaW4vdUpnblhqVVlHZStjSUU4Z3pUN0NKCk5zWWMvUXBUcFhub1hVN3Y4Z0gwT2pwQkFvR0FiL3BBT1FMV1hlNlVZL1NUU2prdU1Fbkg3cU1XU2Y2cFNUdUMKREZlRmtkUTZxMlROeFRTb3hmV0FJSXhwNG1IRlZKY0pscTIwdXowT0RUWUZzL0xvc1JoeGZXQSsrZHE3VXI1TQp6Zk5xcWVRWGtoOWl1Rkc4RXg3TU5oZHh0d0NscWlucE1BZW0vdEZIU0sxY09yTHlMMkdhTzNrb2pFa1l2eWEvCitueWJqMnNDZ1lFQTdFMmI4MDFlRzk2ZzRtdDhjZHRtS2JXZ21GVkh1UjJlTXFwZ0Q2OVZVVEZFQ3dmd0Y0TjcKNm9Bb3JLWDY0QlQ5SE5xTWE4Y1NWRVhqNEk2Z2JkTXpvNys2UGRiYU1ZTEh1eGUxcFN3eVJ3dWhiaUJjSDdNeQpiN1FBTjNTRjR0ZGpnL3ZWc1NVMTVmT3pGbVl6NlpMekcyc0RCWXZaVWdrTHFBMXFkWmcrNHdFPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: bookkeeper-operator/templates/clusterrole.yaml
# @formatter:off
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookkeeper-operator-manager-role
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - apps
      - batch
      - policy
      - extensions
    resources:
      - jobs
      - pods
      - events
      - secrets
      - services
      - configmaps
      - deployments
      - statefulsets
      - poddisruptionbudgets
      - persistentvolumeclaims
    verbs:
      - '*'
---
# Source: bookkeeper-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookkeeper-operator-proxy-role
rules:
  - apiGroups: [ "authentication.k8s.io" ]
    resources:
      - tokenreviews
    verbs: [ "create" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources:
      - subjectaccessreviews
    verbs: [ "create" ]
---
# Source: bookkeeper-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookkeeper-operator-metrics-reader
rules:
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "get" ]
---
# Source: bookkeeper-operator/templates/clusterrolebinding.yaml
# @formatter:off
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bookkeeper-operator-manager-role-binding
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bookkeeper-operator-manager-role
subjects:
  - kind: ServiceAccount
    namespace: bookkeeper-operator
    name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/role.yaml
# @formatter:off
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bookkeeper-operator-leader-election-role
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Source: bookkeeper-operator/templates/rolebinding.yaml
# @formatter:off
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bookkeeper-operator-leader-election-role-binding
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bookkeeper-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    namespace: bookkeeper-operator
    name: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/services.yaml
# @formatter:off
apiVersion: v1
kind: Service
metadata:
  name: bookkeeper-operator-bookkeeper-operator-webhook-service
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: bookkeeper-operator-controller-manager-metrics-service
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  
  selector:
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
---
# Source: bookkeeper-operator/templates/deployment.yaml
# @formatter:off
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookkeeper-operator
  namespace: bookkeeper-operator
  labels:
    helm.sh/chart: bookkeeper-operator-0.2.2
    app.kubernetes.io/name: bookkeeper-operator
    app.kubernetes.io/instance: bookkeeper-operator
    app.kubernetes.io/version: "0.2.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bookkeeper-operator
      app.kubernetes.io/instance: bookkeeper-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bookkeeper-operator
        app.kubernetes.io/instance: bookkeeper-operator
    spec:
      containers:
        - name: bookkeeper-operator
          image: monime/bookkeeper-operator:v0.2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsUser: 65534
          env:
            - name: LEADER_ELECTION_NAMESPACE
              value: bookkeeper-operator
      volumes:
        - name: webhook-certs
          secret:
            secretName: bookkeeper-operator-bookkeeper-operator-webhook-secret
      serviceAccountName: bookkeeper-operator
