# @formatter:off
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "operator.labels" . | nindent 4 }}
  name: {{ template "operator.fullname" . }}