apiVersion: v2
#placeholder: replaced by git tag from CI
version: 0.1.0
#placeholder: replaced by git tag from CI
appVersion: 0.1.0
kubeVersion: ">=1.16.0-0"
type: application
name: bookkeeper-operator
description: A Helm chart for bookkeeper-operator
home: https://github.com/monimesl/bookkeeper-operator
maintainers:
  - name: Monime Team & Open Collaborators