# permissions for end users to edit bookkeeperclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookkeepercluster-editor-role
rules:
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters/status
    verbs:
      - get
