# permissions for end users to edit bookkeeperclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bookkeepercluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bookkeeper-operator
    app.kubernetes.io/part-of: bookkeeper-operator
    app.kubernetes.io/managed-by: kustomize
  name: bookkeepercluster-editor-role
rules:
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - bookkeeper.monime.sl
    resources:
      - bookkeeperclusters/status
    verbs:
      - get
